import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary": "#370096",
        "primary": "#cdbdff",
        "inverse-on-surface": "#303032",
        "tertiary": "#ffb3ae",
        "surface-container-high": "#2a2a2c",
        "surface-tint": "#cdbdff",
        "outline": "#948ea1",
        "surface-variant": "#353437",
        "on-primary-fixed": "#20005f",
        "primary-fixed": "#e8deff",
        "on-primary-container": "#fcf6ff",
        "on-secondary-fixed-variant": "#00531e",
        "primary-container": "#7c4dff",
        "on-secondary-fixed": "#002108",
        "inverse-primary": "#6833ea",
        "error-container": "#93000a",
        "tertiary-container": "#d53338",
        "on-primary-fixed-variant": "#4f00d0",
        "surface": "#131315",
        "on-tertiary-fixed": "#410004",
        "surface-container-highest": "#353437",
        "background": "#131315",
        "surface-container-low": "#1b1b1d",
        "on-background": "#e5e1e4",
        "on-tertiary-container": "#fff6f5",
        "secondary-container": "#02c953",
        "on-surface-variant": "#cac3d8",
        "on-secondary": "#003912",
        "inverse-surface": "#e5e1e4",
        "on-tertiary": "#68000c",
        "surface-bright": "#39393b",
        "error": "#ffb4ab",
        "on-surface": "#e5e1e4",
        "surface-dim": "#131315",
        "on-tertiary-fixed-variant": "#930015",
        "secondary-fixed": "#69ff87",
        "primary-fixed-dim": "#cdbdff",
        "outline-variant": "#494455",
        "surface-container-lowest": "#0e0e10",
        "surface-container": "#201f21",
        "tertiary-fixed-dim": "#ffb3ae",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-container": "#004d1b",
        "on-error": "#690005",
        "secondary-fixed-dim": "#3ce36a",
        "secondary": "#40e56c",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
} satisfies Config
